name: clang-tidy

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: CXX=clang++-18 cmake -Werror=dev -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -B build
    - name: run clang-tidy
      run: run-clang-tidy-18 Source/ -p build/
